---
name: Checks

# trigger is set to push
on: [push]

jobs: 
  test-lint:  
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:     
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: adityatomar1803
          password: dckr_pat_NXrEnARtEGZN0Zrws-amG2M-NT0
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
        # dckr_pat_NXrEnARtEGZN0Zrws-amG2M-NT0